### ISSUE TITLE
Considering that this repo consists of 3 readme files, can we code in here?

### ISSUE THREAD

**Issue by c-goosen** [root-community/root-insurance-python#1]
Hi can we reach out to  [root-insurance-python](https://github.com/BrendanBall/root-insurance-python ) and continue the project here so it can get some help. Then on a make day there is less need to focus on the API and more focus on integrating diagflow to it? @BrendanBall @ncthbrt

**Comment by ncthbrt** [comment]
Yes plz! That'd be fantastic

**Comment by BrendanBall** [comment]
that was why I originally created my repo the day before. Do you guys want to base this off of my repo or have something different in mind? It didn't take long to throw my client together so if someone has something better in mind go ahead.

**Comment by c-goosen** [comment]
Yeah if you are keen then I will move the code in here @BrendanBall and add/fix/etc.

**Comment by c-goosen** [comment]
Your project is a pretty good start and we tried it yesterday

**Comment by BrendanBall** [comment]
go ahead

**Comment by ncthbrt** [comment]
Hey @BrendanBall, would love a PR. We are trying to put all community created SDKs in one place so that people can find them. If you'd like to be added as a community member, give me a shout.
